export interface Person {
  givenName: string;
  surName: string;
  age: Number;
  email: string;
  address: string;
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  education: string;
}

export const ManyPerson: EPerson[] = [
  {
    givenName: 'Sean',
    surName: 'Bryant',
    age: '35',
    email: 'sean_allen_bryant19@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Elizabeth',
    surName: 'Mitchell',
    age: '75',
    email: 'ej@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Haley',
    surName: 'Anderson',
    age: '21',
    email: 'handerson1@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Eric',
    surName: 'Bell',
    age: '71',
    email: 'e_j_bell@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Melissa',
    surName: 'Garcia',
    age: '33',
    email: 'mlgarcia77@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Timothy',
    surName: 'Torres',
    age: '38',
    email: 'timothy_torres49@hotmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Christina',
    surName: 'Jones',
    age: '28',
    email: 'christina.jones@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Eleanor',
    surName: 'Murphy',
    age: '65',
    email: 'eleanor.murphy@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Evelyn',
    surName: 'Johnson',
    age: '20',
    email: 'e.johnson@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Tyler',
    surName: 'Barnes',
    age: '67',
    email: 't.barnes@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Brandon',
    surName: 'Coleman',
    age: '47',
    email: 'brandon_coleman@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Brittany',
    surName: 'Richardson',
    age: '71',
    email: 'brittany_faith_richardson56@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Alexander',
    surName: 'Ross',
    age: '40',
    email: 'alexander.alan.ross@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Emma',
    surName: 'Morgan',
    age: '25',
    email: 'e_r_morgan94@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Lee',
    age: '20',
    email: 'sebastian_lee@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Alexis',
    surName: 'Lewis',
    age: '26',
    email: 'alexis.sue.lewis@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kevin',
    surName: 'Coleman',
    age: '77',
    email: 'k.coleman@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Charlotte',
    surName: 'Adams',
    age: '23',
    email: 'charlotte.f.adams@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Bennett',
    age: '39',
    email: 'victoria_bennett@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Emily',
    surName: 'Russell',
    age: '42',
    email: 'emily.k.russell57@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Rebecca',
    surName: 'Moore',
    age: '77',
    email: 'r_f_moore@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Ryan',
    surName: 'Ramirez',
    age: '73',
    email: 'ryanramirez@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Richard',
    surName: 'Edwards',
    age: '35',
    email: 'r.w.edwards@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Emily',
    surName: 'Jones',
    age: '67',
    email: 'e.jones1@aol.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Grace',
    surName: 'Carter',
    age: '32',
    email: 'g_carter@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Amber',
    surName: 'Taylor',
    age: '29',
    email: 'amber.louise.taylor13@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Powell',
    age: '27',
    email: 's.powell91@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Oliver',
    surName: 'Bryant',
    age: '24',
    email: 'oliverbryant@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Richard',
    surName: 'Thomas',
    age: '57',
    email: 'r_thomas@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Emily',
    surName: 'Hill',
    age: '62',
    email: 'emilyfaith@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Olivia',
    surName: 'Gray',
    age: '42',
    email: 'olivia_gray@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Lillian',
    surName: 'Walker',
    age: '45',
    email: 'lillianmaewalker96@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Christopher',
    surName: 'Green',
    age: '60',
    email: 'ccgreen@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Samantha',
    surName: 'Roberts',
    age: '27',
    email: 's.roberts44@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Ava',
    surName: 'Gray',
    age: '19',
    email: 'avagray@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'David',
    surName: 'Henderson',
    age: '51',
    email: 'david.w@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Robert',
    surName: 'Ward',
    age: '24',
    email: 'r.r.ward@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Brianna',
    surName: 'Carter',
    age: '70',
    email: 'bm@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Nathan',
    surName: 'Collins',
    age: '20',
    email: 'nathan_collins@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Haley',
    surName: 'Campbell',
    age: '29',
    email: 'haley_mary_campbell@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Kelsey',
    surName: 'Turner',
    age: '65',
    email: 'kelsey.turner@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Evans',
    age: '53',
    email: 'tkevans@live.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nicholas',
    surName: 'Roberts',
    age: '20',
    email: 'n.j.roberts@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Heather',
    surName: 'Flores',
    age: '21',
    email: 'h_flores@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Rebecca',
    surName: 'Simmons',
    age: '59',
    email: 'rebeccasimmons@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Aiden',
    surName: 'Price',
    age: '55',
    email: 'a.r.price@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Elizabeth',
    surName: 'Hughes',
    age: '77',
    email: 'elizabeth_hughes@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Daniel',
    surName: 'Rogers',
    age: '71',
    email: 'd.h@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Kaitlyn',
    surName: 'Perry',
    age: '32',
    email: 'k_perry@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Julian',
    surName: 'Williams',
    age: '67',
    email: 'julian_williams33@hotmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Alyssa',
    surName: 'Henderson',
    age: '49',
    email: 'a.l.henderson96@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Zachary',
    surName: 'Reed',
    age: '46',
    email: 'zachary_reed74@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Henry',
    surName: 'Rivera',
    age: '66',
    email: 'henry.rivera9@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nathan',
    surName: 'Lewis',
    age: '40',
    email: 'nathan@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sophia',
    surName: 'Young',
    age: '22',
    email: 's.young@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Alexander',
    surName: 'Lopez',
    age: '60',
    email: 'a_lopez@hotmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Morgan',
    age: '19',
    email: 'victoria_morgan@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Heather',
    surName: 'Wood',
    age: '71',
    email: 'h.m.wood9@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Katherine',
    surName: 'Wilson',
    age: '75',
    email: 'katherine@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Austin',
    surName: 'Kelly',
    age: '77',
    email: 'austin_kelly@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Aaron',
    surName: 'Cooper',
    age: '42',
    email: 'aaron.robert.cooper@aol.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Ethan',
    surName: 'Collins',
    age: '20',
    email: 'ethan_collins@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Henderson',
    age: '72',
    email: 'kyle6@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Ethan',
    surName: 'Reed',
    age: '73',
    email: 'e.j.reed@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Evelyn',
    surName: 'Ward',
    age: '65',
    email: 'e_ward@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Jessica',
    surName: 'Young',
    age: '75',
    email: 'jyoung@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Isaac',
    surName: 'Lopez',
    age: '42',
    email: 'i_lopez@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Kayla',
    surName: 'Moore',
    age: '77',
    email: 'kayla67@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Sara',
    surName: 'Phillips',
    age: '44',
    email: 's.phillips@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Anderson',
    age: '32',
    email: 'shanderson@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Tyler',
    surName: 'Jenkins',
    age: '45',
    email: 't_h_jenkins@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Layla',
    surName: 'Patterson',
    age: '18',
    email: 'l_j_patterson@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Henry',
    surName: 'Reed',
    age: '51',
    email: 'henryreed@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Megan',
    surName: 'Walker',
    age: '56',
    email: 'm.j@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Isaac',
    surName: 'Powell',
    age: '59',
    email: 'i.powell@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Adam',
    surName: 'Hill',
    age: '24',
    email: 'adam@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kimberly',
    surName: 'Richardson',
    age: '49',
    email: 'kimberly_richardson@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jasmine',
    surName: 'Rogers',
    age: '32',
    email: 'jasmine_rogers30@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Amber',
    surName: 'Murphy',
    age: '67',
    email: 'ambermurphy@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Aubrey',
    surName: 'Taylor',
    age: '53',
    email: 'aubrey.r.taylor@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Maria',
    surName: 'Gonzales',
    age: '60',
    email: 'maria.m.gonzales@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Christina',
    surName: 'Jenkins',
    age: '48',
    email: 'christina_jenkins34@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Ethan',
    surName: 'Gonzales',
    age: '30',
    email: 'ethangonzales@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Ava',
    surName: 'Mitchell',
    age: '43',
    email: 'ava_m_mitchell@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Allen',
    age: '68',
    email: 'k_l_allen50@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'James',
    surName: 'Alexander',
    age: '67',
    email: 'jameshenry@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Brian',
    surName: 'Martinez',
    age: '47',
    email: 'brianmartinez@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jonathan',
    surName: 'Johnson',
    age: '43',
    email: 'jonathan.alexander.johnson@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Ryan',
    surName: 'Smith',
    age: '41',
    email: 'ryan.smith@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kevin',
    surName: 'Hughes',
    age: '67',
    email: 'k.h@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Gonzales',
    age: '77',
    email: 'timothy_gonzales@aol.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Lillian',
    surName: 'Walker',
    age: '62',
    email: 'l.a@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Olivia',
    surName: 'Martin',
    age: '44',
    email: 'olivia_renee_martin@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Benjamin',
    surName: 'Torres',
    age: '30',
    email: 'benjaminatorres49@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sofia',
    surName: 'Bryant',
    age: '36',
    email: 's_bryant@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Ryan',
    surName: 'Bryant',
    age: '50',
    email: 'ryan@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Christopher',
    surName: 'Long',
    age: '36',
    email: 'c.long@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Allison',
    surName: 'Jones',
    age: '21',
    email: 'aljones@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Ryan',
    surName: 'Morgan',
    age: '59',
    email: 'ryan.morgan@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Kelsey',
    surName: 'Green',
    age: '50',
    email: 'kelsey.grace.green@aol.com',
    education: 'Less than high school',
  },
];
